### ISSUE TITLE
Not worked

### ISSUE THREAD

**Issue by advphp** [navin-hariharan/TeleRat#1]
When I run the telerat.py file the program does not work
It continues in sleep mode

https://imgur.com/a/hykzfpx

**Comment by navin-hariharan** [comment]
@advphp That is not broken! 
Please use the build.exe to build **_TELERAT_**

The console does not print anything has the malware shouldn't print anything when it's running on the target system! Has it would reveal the anonymity. 

--------------------------------------------------------------------------------------------------------------------------------------------
Even if you are using the python file directly for testing... Make sure you have set and configured the BOT API for the telegram! However, I do not recommend this...
